task_type: video_segment
model:
  checkpoint: autolabel/checkpoints/sam2_hiera_large.pt
  model_cfg: sam2_hiera_l.yaml
source: autolabel/images/10.avi
prompt:
  point_coords:
    - [768, 108]
  point_labels: [1]
  # box: [425, 600, 700, 875]
